### ISSUE TITLE
"Unhandled exception" blocks all outputs. (Logstash 1.5.6)

### ISSUE THREAD

**Issue by esolitos** [cyli/logstash-output-slack#18]
Hello,
  I'm not 100% sure that the problem is in this output module, but I must start somewhere.
Every now and then Slack replies with a "Connection Refused" to my logstash and as a result the whole output stops working (including _all other outputs_) until I manually restart the whole application.
Needless to say this is terrible, since I need to constantly check that it's still working.

This is the unhandled exception stacktrace:

```
"Unhandled exception", :exception=>#<Errno::ECONNREFUSED: Connection refused - Connection refused>, :stacktrace=>[
"org/jruby/ext/socket/RubyTCPSocket.java:126:in `initialize'",
"org/jruby/RubyIO.java:1179:in `open'",
"/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:763:in `connect'",
"org/jruby/ext/timeout/Timeout.java:98:in `timeout'",
"/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:763:in `connect'",
"/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:756:in `do_start'",
"/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:745:in `start'",
"/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:744:in `start'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-slack-0.1.1/lib/logstash/outputs/slack.rb:64:in `receive'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/outputs/base.rb:88:in `handle'",
"(eval):3237:in `output_func'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/pipeline.rb:244:in `outputworker'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/pipeline.rb:166:in `start_outputs'"
],
:level=>:warn}
```

**Comment by esolitos** [comment]
This is not related to this plugin. sorry.
